### PR TITLE
Dummy data and initial SQL setup

### PR DESCRIPTION
**Pull request by jmskinne**
`git fetch --all`
`git checkout initial-sql`

1. Includes  create tables based on ERD
1. Includes dummy data
1. Includes select and join statements to make sure queries are running properly
(I believe you may need to create your own rare.db file and connect through sqlite)

### CODE REVIEW

**Comment by MoSilvera** [comment]
You all should pick a template for your pull requests (more robust than this one in the future)

**Comment by petestewart** [comment]
lines `93` and `94` are missing semicolons, but other than that everything seems to work

**Comment by jmskinne** [comment]
added missing semicolons

**Review by petestewart — APPROVED** [review]
👍

**Review by christopherjohnson1 — APPROVED** [review]
👍

**Pull request merged**
